### ISSUE TITLE
Validator doesn't check for "additionalProperties = false"

### ISSUE THREAD

**Issue by TarasBK** [lezhnev74/openapi-psr7-validator#31]
There is another issue had been found out during testing. Comment in source file https://github.com/lezhnev74/openapi-psr7-validator/blob/master/src/Schema/Keywords/Properties.php describes behaviour for "additionalProperties = false" option, but it seems, there is no check in actual code.

And here is OpenAPI documentation for reference: https://swagger.io/specification/#schemaObject.

**Comment by lezhnev74** [comment]
@TarasBK can you provide your schema and the message that you validate? I'll make a test to confirm that and write a patch.

**Comment by TarasBK** [comment]
Of course.
Definition:
``` yaml
testSchema:
  type: object
  required:
    - data
  properties:
    data: {}
  additionalProperties: false
```
Object to validate:
``` json
{
  "data": {},
  "excessProperty": "test"
}
```

This should throw some exception, for example: 
> The property excessProperty is not defined and the definition does not allow additional properties
