### ISSUE TITLE
Query string parameter validation of Arrays with `style: form` and `explode: false`

### ISSUE THREAD

**Issue by digilist** [lezhnev74/openapi-psr7-validator#38]
Consider this swagger parameter definition (in YAML):
```yaml
    -
        name: filter
        in: query
        description: Filter something
        explode: false
        style: form
        schema:
            type: array
            items:
                type: string
```

According to the [Open Api Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-examples) this will result in a query parameter  `?filter=a,b,c` (which is also generated by Swagger UI)

However, the validation does not consider a URL of that format as an array, but as a string:

```
OpenAPI spec does not match the query argument 'with' of the request [/test,get]: Value expected to be 'array', 'string' given.
```
