### ISSUE TITLE
Bug with numeric strings

### ISSUE THREAD

**Issue by vsouz4** [lezhnev74/openapi-psr7-validator#58]
I have in definition something like:
```
    patch:
      summary: Do Something
      description: Do Something
      operationId: someOperation
      parameters:
        - name: id
          in: path
          description: ID of something
          required: true
          schema:
            type: string
```
and this throws me an error when the request contains a numeric string (which is possible):
```
Argument 2 passed to OpenAPIValidation\\PSR7\\Exception\\Validation\\InvalidPath::becauseValueDoesNotMatchSchema() must be of the type string, integer given, called in /srv/app/vendor/lezhnev74/openapi-psr7-validator/src/PSR7/Validators/PathValidator.php on line 56
```
That happens because on `lezhnev74/openapi-psr7-validator/src/PSR7/Validators/PathValidator.php`:
```php
        foreach ($pathParsedParams as $name => $value) {
            try {
                $validator->validate($value, $specs[$name]->schema);
            } catch (SchemaMismatch $e) {
                throw InvalidPath::becauseValueDoesNotMatchSchema($name, $value, $addr, $e);
            }
        }
```
`$value` is integer; you're parsing parameters with:
```php
            // cast numeric
            if (is_numeric($value)) {
                $value += 0; // that will cast it properly
            }
```
on `lezhnev74/openapi-psr7-validator/src/PSR7/OperationAddress.php`
but then on `lezhnev74/openapi-psr7-validator/src/PSR7/Exception/Validation/InvalidPath.php` you're type hinting with `string`:
```php
    public static function becauseValueDoesNotMatchSchema(string $parameterName, string $parameterValue, OperationAddress $address, SchemaMismatch $prev) : self
    {
        $exception          = static::fromAddrAndPrev($address, $prev);
        $exception->message = sprintf('Value "%s" for parameter "%s" is invalid for %s', $parameterValue, $parameterName, $address);
```
so maybe you don't cast it or remove type hinting from `InvalidPath`?
